language: groovy
before_install:
- chmod +x gradlew
deploy:
  api_key:
    secure: VmEpx1+X6G8ui1y/Mk2VEDD2I4F3LK3DpMANRqqQAfY5C7xh9UFf0UCT8/nDzGwteHzXNZ3QrpCZQFwO3rbKSrEBmJFTJQkNa8+3DtD+zlvedKc0cOnJNmjajS+D/RrQmz1+RraM0WwE5IEOGPOaw6UMeldD3gYnnS0NNugCp33wKkBeRmQbcAtveqKRc1vQmFHWZQufbGf7Z5Wti16DCuQ3rdEVSx8N7bkbJxjz7tcTHEXeVJM8W+VPcAcbiFiCHtN36KmlxFQiztoNGo6nMfLeQGi1KMOga5LxYm+o0aXP2j04448EJ7X9VEn0AjzogdlNZVXE+vJZ6nBgOa3O5Uj6vJaAe8ejLyxiI4JiCxMn+YyWPpWsNZrONjlFMTwQQpmACkYnZ6rMREvKCQI5JtIDdxafOY47gs2JjkKV5BzBYU+eTfu+TsNQMhyMWkXPxNn7recPRiI00rcuneTTLdqsbufMHQOC+7qbYrC60H7DWCPS9pmW+NNNQHaPbY9oJR5ugkvM741gh9yvtOPey2+y22FjAzCB46b9Jx9/UgJDQKcN+WHlXqOaQysAWXvaBLYJwQHg1YWJ8e68TulqQ2EOidsf+AcvAPgOLnmhsKf2Hv7BLza+GOFKktpaeLen0v7dIlYnrxoPHwf3i+tGJ9eK2aY2lesu4ot85YEuysU=
  app: boiling-brushlands-56239
